version: "3.8"

services:
  laravelapp:
    env_file: .env
    container_name: ${CONTAINER_NAME_PREFIX}app
    build:
      context: ./build
      args:
        PROJECT_PATH: ${PROJECT_PATH}
        PHP_FPM_VERSION: ${PHP_FPM_VERSION}
        INSTALL_NODEJS: ${INSTALL_NODEJS}
    restart: unless-stopped
    tty: true
    working_dir: ${PROJECT_PATH}
    depends_on:
      - laraveldb
    volumes:
      - ./code:${PROJECT_PATH}
      - ./build/php/php-fpm.d/www2.conf:/usr/local/etc/php-fpm.d/www2.conf
      - ./build/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      local:
        aliases:
          - ${NETWORK}

  laraveldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${CONTAINER_NAME_PREFIX}db
    restart: unless-stopped
    ports:
      - ${HOST_DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laraveldb:/var/lib/mysql/
      - ./build/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      local:
        aliases:
          - ${NETWORK}
  
  laravelweb:
    image: nginx
    container_name: ${CONTAINER_NAME_PREFIX}web
    ports:
      - ${NGINX_HTTP_PORT}:80
      #- ${NGINX_HTTPS_PORT}:443
    volumes:
      - ./build/nginx/conf.d/:/etc/nginx/conf.d/
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./code:${PROJECT_PATH}:consistent
      - ./build/nginx/log:/var/log/nginx
    depends_on:
      - laravelapp
    networks:
      local:
        aliases:
          - ${NETWORK}

  laravelredis:
    image: redis
    volumes:
        - ./build/data/redis:/datadoc
    container_name: ${CONTAINER_NAME_PREFIX}redis
    ports:
        - "6379:6379"
    networks:
      local:
        aliases:
          - ${NETWORK}
#Docker Networks
networks:
  local:
    name: ${NETWORK}
#Volumes
volumes:
  laraveldb:
    name: ${CONTAINER_NAME_PREFIX}db
